name: 🚀 Test & Deploy Angular + Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Build & Test Angular
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Instalar Dependências
        run: npm install

      - name: Compilar a Aplicação Angular
        run: npm run build -- --configuration=production

      - name: Rodar Testes Unitários
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

  terraform:
    name: Deploy Infra AWS
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar Terraform
        run: terraform validate

      - name: Aplicar Terraform (Criar Infra)
        run: terraform apply -auto-approve

      - name: Mostrar Outputs da Infraestrutura
        run: terraform output